# Generated by Django 4.0.2 on 2022-02-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('home_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=30)),
                ('profession', models.CharField(choices=[('Nurses', 'Nurses'), ('Healthcare Assistants', 'Healthcare Assistants')], max_length=255)),
                ('statement', models.BooleanField(choices=[('Qualified nurse with current NMC pin number', 'Qualified nurse with current NMC pin number'), ('Qualified theature nurse with current HPC number', 'Qualified theature nurse with current HPC number'), ('Expeienced Helathcare assitstand', 'Expeienced Helathcare assitstand')])),
                ('experience', models.CharField(blank=True, max_length=20, null=True)),
                ('visa_status', models.BooleanField(choices=[('Need for work permit,eligible to work in UK', 'Need for work permit,eligible to work in UK'), ('With work permit,eligible work in UK', 'With work permit,eligible work in UK'), ('In the process of obtaining work permit to work in UK', 'In the process of obtaining work permit to work in UK')])),
                ('upload_CV', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('additional_info', models.TextField(max_length=2000)),
            ],
        ),
    ]
