# Generated by Django 4.0.2 on 2022-02-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carehub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='statement',
            field=models.CharField(choices=[('1', 'Qualified nurse with current NMC pin number'), ('2', 'Qualified theature nurse with current HPC number'), ('3', 'Expeienced Helathcare assitstand')], max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='visa_status',
            field=models.CharField(choices=[('1', 'Need for work permit,eligible to work in UK'), ('2', 'With work permit,eligible work in UK'), ('3', 'In the process of obtaining work permit to work in UK')], max_length=255),
        ),
    ]
