# Generated by Django 4.0.2 on 2022-02-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carehub', '0003_alter_registration_upload_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='middle_name',
        ),
    ]
