# Generated by Django 4.0.2 on 2022-02-20 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carehub', '0004_remove_registration_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='application_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('1', 'Un-Responded'), ('2', 'Responded')], default='Un-Responded', max_length=255),
        ),
    ]
