# Generated by Django 4.0.2 on 2022-02-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carehub', '0005_registration_application_date_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('Un-Responded', 'Un-Responded'), ('Responded', 'Responded')], default='Un-Responded', max_length=255),
        ),
    ]
