# Generated by Django 4.0.2 on 2022-02-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carehub', '0006_alter_registration_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('appointment_on', models.DateField()),
                ('interested_for', models.CharField(choices=[('Agency Staffs', 'Agency Staffs'), ('Recruitment', 'Recruitment'), ('Training', 'Training')], max_length=255)),
                ('messages', models.TextField()),
            ],
        ),
    ]
