# Generated by Django 4.0.2 on 2022-02-20 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carehub', '0007_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='application_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Un-Responded', 'Un-Responded'), ('Responded', 'Responded')], default='Un-Responded', max_length=255),
        ),
    ]
