# Generated by Django 4.0.2 on 2022-02-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carehub', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('Un-Responded', 'Un-Responded'), ('Responded', 'Responded')], default='Un-Responded', max_length=255),
        ),
    ]
